# Generated by Django 2.0.2 on 2018-03-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pebookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
