# Generated by Django 2.0.2 on 2018-03-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pebookingsystem', '0002_auto_20180329_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name_plural': 'schoolclasses'},
        ),
    ]
