# Generated by Django 2.0.2 on 2018-04-12 14:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pebookingsystem', '0003_auto_20180329_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=30),
        ),
    ]
