# Generated by Django 2.0.2 on 2018-04-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pebookingsystem', '0004_auto_20180412_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsevening',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
