# Generated by Django 2.0.2 on 2018-04-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pebookingsystem', '0005_auto_20180413_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='classname',
            field=models.CharField(default='test', max_length=256),
            preserve_default=False,
        ),
    ]
